/* eslint-disable import/no-cycle */

// AUTH
export const GET_EXTRY_AND_EXIT_TYPE = "GET_EXTRY_AND_EXIT_TYPE";
export const GET_EXTRY_AND_EXIT_TYPE_SUCCESS =
  "GET_EXTRY_AND_EXIT_TYPE_SUCCESS";
export const GET_EXTRY_AND_EXIT_TYPE_ERROR = "GET_EXTRY_AND_EXIT_TYPE_ERROR";

export const POST_EXTRY_AND_EXIT_TYPE = "POST_EXTRY_AND_EXIT_TYPE";
export const POST_EXTRY_AND_EXIT_TYPE_SUCCESS =
  "POST_EXTRY_AND_EXIT_TYPE_SUCCESS";
export const POST_EXTRY_AND_EXIT_TYPE_ERROR = "POST_EXTRY_AND_EXIT_TYPE_ERROR";
